### ISSUE TITLE
Adding HAT to HuggingFace Transformers

### ISSUE THREAD

**Issue by NielsRogge** [coastalcph/hierarchical-transformers#1]
Hi,

Congrats on this work :) I've started implementing HAT as a branch of 🤗 Transformers, it can be found here: https://github.com/NielsRogge/transformers/tree/add_hat/src/transformers/models/hat.

However, the main job now is to make sure all tests pass. These can be run from the root of the repo as follows:

```
RUN_SLOW=yes pytest tests/models/hat/test_modeling_hat.py
```
As I'm not familiar with the internals of HAT, would you be up for making these tests pass?

Typically, models are tested with tiny variants, e.g. we set the hidden_size to only 32 and the number of layers to 3. However, currently many tests are failing:

```
num_sentences = 0, max_sentence_length = 128

    def transform_tokens2sentences(hidden_states, num_sentences, max_sentence_length):
        # transform sequence into segments
>       seg_hidden_states = torch.reshape(
            hidden_states, (hidden_states.size(0), num_sentences, max_sentence_length, hidden_states.size(-1))
        )
E       RuntimeError: shape '[1, 0, 128, 768]' is invalid for input of size 8448
```

Let me know if you want to work on this.

Cheers,

Niels
ML Engineer @ HuggingFace

**Comment by iliaschalkidis** [comment]
Hi @NielsRogge, Thanks for taking this initiative. I already started locally last week following the documentation. I'll have to go over the tests and keep those applicable since HAT do no support encoder-decoder models... I'm in a medical emergency right now, I'll get back asap !

**Comment by iliaschalkidis** [comment]
5 months later still can't find time to invest on this. The code supports encoder-only models, and the test have to be rewritten for this purpose. I would be glad if someone else can look into this integration. Thanks!
