### ISSUE TITLE
Extracting the Cross Segment Encoder Attention Matrices

### ISSUE THREAD

**Issue by sriramsk1999** [coastalcph/hierarchical-transformers#4]
Hi, thanks for releasing your work. 

I'm trying to extract the attentions for a given input, but for the CSE layers. This is what I have right now:

```py
doc_model = AutoModelForSequenceClassification.from_pretrained("kiddothe2b/hierarchical-transformer-base-4096", trust_remote_code=True, output_attentions=True)

attention = doc_model(input_ids, attention_mask)['attentions']
```

With a `max_length` of 1024 I get a matrix of the following shape - `12 x 8 x 12 x 128 x 128`. If I understand correctly, this is `nLayers X nSegments x nHeads x segmentSize x segmentSize`.

This seems to be the attentions of the SWE blocks, as you mention in the paper that `segmentSize=128` and that 12 out of 16 layers are SWE blocks. I would like to extract the CSE attentions, which I expect should have the following shape - `4 x 1 x 12 x 8 x 8`. How do I extract these attentions?

**Comment by sriramsk1999** [comment]
Found a workaround for this digging through the source code. For future reference:

Looks like huggingface's `AutoModel` does not support the additional return field needed for CSE attentions. However, the `HATModelForSequentialSentenceClassification` class in the `modelling_hat.py` does support it. So all I had to do was bring `modeling_hat.py` into my project and rewrite as follows. 

```py
from modelling_hat import HATModelForSequentialSentenceClassification
doc_model = HATModelForSequentialSentenceClassification.from_pretrained("kiddothe2b/hierarchical-transformer-base-4096", trust_remote_code=True, output_attentions=True)

outputs = doc_model(input_ids, attention_mask)
attention = outputs['attention']
sentence_attention = outputs['sentence_attention'] # The attention matrices of the CSE blocks
```
  
Would be nice to have it directly accessible through `AutoModel`, though I'm not sure if huggingface supports it. Thanks for the clean code, it made finding a solution a lot easier :)

**Comment by iliaschalkidis** [comment]
Hi @sriramsk1999, I'm glad you found the solution. I should probably include this detail in the README file.
