### ISSUE TITLE
Maximum context length?

### ISSUE THREAD

**Issue by Tylersuard** [coastalcph/hierarchical-transformers#7]
Hello.  I noticed that you were able to classify documents up to 6,000+ tokens in length.  Do you know the absolute maximum context length the HAT can work with?  Great idea by the way!

**Comment by Tylersuard** [comment]
As a follow-up question, have you thought about having a third layer of abstraction (attention across groups of segments), or even a fourth?

**Comment by iliaschalkidis** [comment]
Hi @Tylersuard,

> Hello. I noticed that you were able to classify documents up to 6,000+ tokens in length. Do you know the absolute maximum context length the HAT can work with? Great idea by the way!

There is no hard limit, as long as you train a HAT with increased `max_sentence_length`, `max_sentences`, and `model_max_length` (=  `max_sentences` * `max_sentence_length`), and `max_position_embeddings` (= `max_sentence_length` + 2), all parameters in the configuration file `config.json`. It depends on the hardware you have to support the increased document length.



> As a follow-up question, have you thought about having a third layer of abstraction (attention across groups of segments), or even a fourth?

Sure, you can rely on the current implementation (https://github.com/coastalcph/hierarchical-transformers/blob/main/models/hat/modelling_hat.py), modify it and add new levels of abstractions with minimal changes.

**Comment by Tylersuard** [comment]
@iliaschalkidis Thank you.  I will work on this.  It seems to me that a balance between number of abstraction layers may be key to a longer context length consuming few resources.  For example maybe 10 abstraction layers would be too many, 2 may be too few, but maybe somewhere in between would be a sweet spot, that would allow a context length of 100k+ tokens without too much resource usage.  I will do my own experiments and see how things go.  Thank you!
