### ISSUE TITLE
Error when attempting to run Colab:

### ISSUE THREAD

**Issue by Tylersuard** [coastalcph/hierarchical-transformers#8]
Here is the command I am running:
python language_modelling/xla_spawn.py --num_cores=8 language_modelling --dataset_name multi_eurlex --dataset_config_name en --line_by_line 1 --do_train 1 --do_eval 1 --output_dir data/PLMs --overwrite_output_dir 1 --evaluation_strategy epoch --save_strategy epoch --save_total_limit 5 --num_train_epochs 3 --learning_rate 1e-5  --per_device_train_batch_size 16 --per_device_eval_batch_size 16 --gradient_accumulation_steps 1 --eval_accumulation_steps 1 --warmup_ratio 0.1 --weight_decay 0.01 --adam_epsilon 1e-6 --max_seq_length 8192 --max_train_samples 64 --max_eval_samples 64 --pad_to_max_length 1

And here is the error:

Traceback (most recent call last):
  File "language_modelling/xla_spawn.py", line 85, in <module>
    main()
  File "language_modelling/xla_spawn.py", line 81, in main
    xmp.spawn(mod._mp_fn, args=(), nprocs=args.num_cores)
AttributeError: module 'language_modelling' has no attribute '_mp_fn'

**Comment by iliaschalkidis** [comment]
In a non-TPU environment, you should exclude the `language_modelling/xla_spawn.py --num_cores=8` from your call. I suggest activating a GPU backend on the collab and possibly also decrease the `max_train_samples/max_eval_samples` and use gradient accumulation instead.

Try:

```
python language_modelling ...
```

**Comment by Tylersuard** [comment]
This was a TPU environment, I was using Google Colab.
