### ISSUE TITLE
Where do we download the Wikipedia files? (train_hi_transformer.sh not working)

### ISSUE THREAD

**Issue by Tylersuard** [coastalcph/hierarchical-transformers#9]
for key, example in ex_iterable:  File "/usr/local/envs/py37/lib/python3.7/site-packages/datasets/i  File "/usr/local/envs/py37/lib/python3.7/site-packages/datasets/iterable_dataset.py", line 652, in __iter__    yield from self._iter()  File "/usr/local/envs/py37/lib/python3.7/site-packages/datasets/iterable_dataset.py", line 667, in _iter    for key, example in iterator:  File "/usr/local/envs/py37/lib/python3.7/site-packages/datasets/iterable_dataset.py", line 1088, in __iter__    for key, example in self.ex_iterable:  File "/usr/local/envs/py37/lib/python3.7/site-packages/datasets/iterable_dataset.py", line 207, in __iter__    yield from self.generate_examples_fn(**self.kwargs)  File "/root/.cache/huggingface/modules/datasets_modules/datasets/wikipedia-dataset/29ec1744832ecf45af70dff54b5c8fe2a5cfa430a978822adbc66af3d6b11156/wikipedia-dataset.py", line 134, in _generate_examples    for path, f in files:  File "/usr/local/envs/py37/lib/python3.7/site-packages/datasets/download/streaming_download_manager.py", line 881, in __iter__    yield from self.generator(*self.args, **self.kwargs)  File "/usr/local/envs/py37/lib/python3.7/site-packages/datasets/download/streaming_download_manager.py", line 932, in _iter_from_urlpath    with xopen(urlpath, "rb", use_auth_token=use_auth_token) as f:  File "/usr/local/envs/py37/lib/python3.7/site-packages/datasets/download/streaming_download_manager.py", line 493, in xopen    return open(main_hop, mode, *args, **kwargs)FileNotFoundError: [Errno 2] No such file or directory: 'data/wikipedia-dataset/wikipedia.20200501.en.tar.gz'

**Comment by iliaschalkidis** [comment]
It seems that HuggingFace hosts, only the latest Wikipedia dump at a time (https://huggingface.co/datasets/wikipedia). Also the `wikipedia` dataset is not streamable, so I saved some of the articles locally and used a custom streamable loader. You can either download the latest English dump and update the custom loader (https://github.com/coastalcph/hierarchical-transformers/blob/main/data/wikipedia-dataset/wikipedia-dataset.py) or use a streamable dataset like C4.

```python
from datasets import load_dataset
dataset = load_dataset("wikipedia", "20220301.en")
dataset = load_dataset("c4", "en", streaming=True)

```
